Aamer Hasham's Week One Assignment
calvintennant/gbc_comp-9635_03 pull request #13
Opened 2018-01-31 03:21 UTC by aamernhasham

Successfully created a basic portfolio site with limited content and creating a pull request.

2018-02-03 18:00 UTC, calvinte requested changes
It looks like you've made some changes that I can't approve. The `index.js` and `package.json` files from `week_1/tennant-calvin` were moved to your directory (they should have been copied). 

Additionally there is a new file `week_2/~$README.md` which should be removed. 

Please review. If you have any difficulty with this please see me in class. Thanks!

2018-02-04 17:32 UTC, aamernhasham commented
Hello Calvin,

So, I have made the changes you've requested (added package.json and index.js files back). In addition, removed the week_2/~$README.md file. 

Do I need to perform a NEW pull request? Please let me know.

Thanks,

Aamer

2018-02-08 17:57 UTC, calvinte approved these changes

2018-02-08 17:57 UTC, merged

2018-02-08 17:57 UTC, calvintennant commented
Looks good to me!