Week 1 Assignment
calvintennant/gbc_comp-9635_03 pull request #7
Opened 2018-01-26 01:32 UTC by rwhammond

2018-02-02 03:56 UTC, rwhammond commented
Week 2 assignment

2018-02-03 18:10 UTC, calvinte requested changes
It looks like you've made some changes that I can't approve.

The `package.json` file from `week_1/tennant-calvin` was moved to your directory (it should have been copied).

The `index.js` file from `week_1/lastname-firstname` was moved to `week_2/hammond-ryan` (it should have been copied).

Additionally the file `week_1/lastname-firstname/src/index.html` was deleted in your copy of the repository. 

Additionally `week_2/README.md` was modified.

Please review. If you have any difficulty with this please see me in class. Thanks!

2018-02-05 00:26 UTC, rwhammond commented
Downloaded your repo again. Should be okay.

2018-02-16 04:13 UTC, calvinte approved these changes

2018-02-16 04:13 UTC, merged